p8105_hw2_ym3077
================

## Problem 1

Load library

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(lubridate)
library(readxl)
```

Load datasets

``` r
pols_df = read_csv("./data/pols-month.csv")
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_df = read_csv("./data/snp.csv")
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemp_df = read_csv("./data/unemployment.csv")
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Clean pols_df

``` r
pols_df_clean = pols_df |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) |>
  mutate(
    month = month.name[month],
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem"
    )
  ) |>
  select(-day, -prez_gop, -prez_dem)
```

Clean snp_df

``` r
snp_df_clean = snp_df |>
  mutate(date = mdy(date)) |>                        
  mutate(
    year = year(date),                               
    month = month(date, label = TRUE, abbr = FALSE), 
    day = day(date)                                   
  ) |>
  select(year, month, day, close) |>
  arrange(year, month)
```

Clean unemp_df

``` r
unemp_df_clean = unemp_df |>
  janitor::clean_names() |> 
  pivot_longer(
    jan:dec,                
    names_to = "month",
    values_to = "unemployment"
  ) |>
  mutate(
    month = month.name[match(month, tolower(month.abb))],
    year = year
  ) |>
  select(year, month, unemployment) |>
  arrange(year, match(month, month.name))
```

Merge 3 datasets

``` r
merged_df = pols_df_clean |>
  left_join(snp_df_clean, by = c("year", "month")) |>
  left_join(unemp_df_clean, by = c("year", "month"))

merged_df
```

    ## # A tibble: 822 × 12
    ##     year month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president   day
    ##    <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <int>
    ##  1  1947 January      23      51     253      23      45     198 dem          NA
    ##  2  1947 Februa…      23      51     253      23      45     198 dem          NA
    ##  3  1947 March        23      51     253      23      45     198 dem          NA
    ##  4  1947 April        23      51     253      23      45     198 dem          NA
    ##  5  1947 May          23      51     253      23      45     198 dem          NA
    ##  6  1947 June         23      51     253      23      45     198 dem          NA
    ##  7  1947 July         23      51     253      23      45     198 dem          NA
    ##  8  1947 August       23      51     253      23      45     198 dem          NA
    ##  9  1947 Septem…      23      51     253      23      45     198 dem          NA
    ## 10  1947 October      23      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 2 more variables: close <dbl>, unemployment <dbl>

Summary:

Three datasets: `pols_df`, `snp_df`, and `unemp_df`, each containing
monthly-level U.S. data.  
- The `pols_df` dataset provides information on political composition,
including 9 variables such as `year`, `month`, `gov_gop`, `gov_dem`,
`sen_gop`, `sen_dem`, `rep_gop`, and `president` indicating the number
of officeholders from each party.  
- The `snp_df` dataset includes stock market data with 2 variables：
`date` and `close`, where close records the closing values of the S&P
stock index on the associated date.  
- The `unemp_df` dataset reports national unemployment rates, originally
with columns for each month (Jan to Dec) and a Year column, 68
observations of 13 variables in total:, later pivoted into long format
with variables `year`,`month`, and `unemployment`.

After cleaning and transforming the individual datasets, they were
merged using common keys year and month, resulting in a single dataset
`merged_df` with 822 rows and 12 columns, spanning the years 1947 to
2015. The merged dataset includes key variables such as `year`, `month`,
`president`, `close` (S&P index), and `unemployment`, allowing for
integrated analysis of political control, economic conditions, and
market trends across nearly seven decades.

## Problem 2

Read and clean Mr. Trash Wheel data

``` r
mr_trash <- read_excel("data/202409 Trash Wheel Collection Data.xlsx",
                       sheet = "Mr. Trash Wheel", skip = 1) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(
    sports_balls = as.integer(round(sports_balls, 0)),
    year = as.integer(year),
    trash_wheel = "Mr. Trash Wheel" 
  ) |>
  select(dumpster, month, year, date, weight_tons, volume_cubic_yards,
         plastic_bottles, polystyrene, cigarette_butts, glass_bottles, plastic_bags,
         wrappers, sports_balls, homes_powered, trash_wheel)
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

Read and clean Professor Trash Wheel data

``` r
prof_trash <- read_excel("data/202409 Trash Wheel Collection Data.xlsx",
                         sheet = "Professor Trash Wheel", skip = 1) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    trash_wheel = "Professor Trash Wheel")
```

Read and clean Gwynnda data

``` r
gwynnda_trash <- read_excel("data/202409 Trash Wheel Collection Data.xlsx",
                            sheet = "Gwynnda Trash Wheel", skip = 1) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    trash_wheel = "Gwynnda Trash Wheel")
```

Combine all Trash Wheel datasets

``` r
trash_wheel_all <- bind_rows(mr_trash, prof_trash, gwynnda_trash)

trash_wheel_all
```

    ## # A tibble: 1,033 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,023 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

The combined dataset contains 1033 observations of trash collection
records from 3 Trash Wheels in Baltimore: Mr. Trash Wheel, Professor
Trash Wheel, and Gwynnda Trash Wheel. Each observation corresponds to a
dumpster load of trash, and includes key variables such as the date of
collection, weight in tons of trash collected (`weight_tons`), volume in
cubic yards (`volume_cubic_yards`), and itemized counts of different
trash types like plastic bottles, polystyrene, cigarette butts, glass
bottles, plastic bags, etc. A notable variable is `homes_powered`,
estimating the number of homes that could be powered using the energy
from incinerated trash.

For the available data, Professor Trash Wheel collected a total of
246.74 tons of trash. In June 2022, Gwynnda collected a total of
1.812^{4} cigarette butts.
